# Generated by Django 4.1 on 2022-08-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='descripcion de la tarea')),
                ('states', models.TextField(choices=[('TODO', 'Por hacer'), ('DONE', 'Hecha')], default='TODO', verbose_name='Estado de la tarea')),
            ],
        ),
    ]
